/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        try {
            int x = 1 / 0;
        } catch (Exception e) {
            e.printStackTrace(); //Comment this line to force SonarQube to report an issue and be non compliant 
        }
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }   
}
