/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
       // to show sonar failing we need remove the comment block around
       // the try and catch block below by removing the /* and */ characters

       /* 
        try {
            int x = 1 / 0;
        } catch (Exception e) {
            e.printStackTrace();  
        }
        */

        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }   
}
