pipeline {

    environment {
        KOSLI_ORG = 'kosli-public'
        KOSLI_API_KEY = credentials('kosli-api-key')

    }
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from the repository
                checkout scm
            }
        }
        stage('Setup') {
            steps {
            // Change to the app directory
                dir('app') {
                    // Run any setup commands here
                    sh 'ls -al'
                    sh 'kosli list envs'
                }
            }
        }
        stage('Build') {
            steps {
                dir('app') {
                    // Run the Gradle build
                    sh './gradlew build'
                }
            }
        }

        stage('Test') {
            steps {
                dir('app') {
                    // Run the Gradle tests
                    sh './gradlew test'
                }
            }
        }

        stage('Archive') {
            steps {

                // Archive the build artifacts
                archiveArtifacts artifacts: 'app/build/libs/*.jar', allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            // Clean up the workspace after the build
            cleanWs()
        }
    }
}