name: Kosli report

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

env:
  KOSLI_ORG: kosli-public
  KOSLI_API_TOKEN: "${{ secrets.KOSLI_API_TOKEN_PUBLIC }}"

jobs:
  report:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.3.1
      with:
        role-to-assume: arn:aws:iam::329991379326:role/${{ github.event.repository.name }}
        aws-region: eu-central-1
        role-duration-seconds: 900
        role-session-name: ${{ github.run_id }}

    - name: Set up kubeconfig
      run: |
        mkdir -p ~/.kube
        aws eks update-kubeconfig --name kosli-demo

    - name: Setup Kosli cli
      uses: kosli-dev/setup-cli-action@v2
      with:
        version:
          ${{ vars.KOSLI_CLI_VERSION }}

    - name: Kosli report staging
      run: |
        kosli snapshot k8s jenkins-java-example-staging -n staging

    - name: Kosli report production
      run: |
        kosli snapshot k8s jenkins-java-example-prod -n production
