name: Trigger Jenkins Pipeline

on:
  push:
    branches:
      - 'shared-jenkins'

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Check IP and Trigger Jenkins Job
        run: |
          echo "Checking IP address..."
          curl -s https://api.ipify.org
          echo -e "\n\nTriggering Jenkins job..."
          curl -XL POST "https://jenkins.kosli.tools/job/jenkins-example/build" \
            --user "${{ secrets.JENKINS_USER_TEST }}:${{ secrets.JENKINS_API_TOKEN_TEST }}" \
            --data-urlencode json="{
              \"parameter\": [
                {\"name\": \"GIT_BRANCH\", \"value\": \"${{ github.ref }}\"},
                {\"name\": \"GIT_COMMIT\", \"value\": \"${{ github.sha }}\"},
                {\"name\": \"GIT_REPO\", \"value\": \"${{ github.repository }}\"}
              ]
            }" 